<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.54" os="Windows 7" host="USER-185"><DocLocation><![CDATA[D:\Tap_Framework\TAP\Scripts\SAP_win_Login]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[SAP_win_Login]]></DName>
<Res><![CDATA[Res50]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[02-01-2017 - 12:51:36]]></Time>
<TimeTick>1483341696</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="8" status="Passed" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[02-01-2017 - 12:51:36]]></Time>
<TimeTick>1483341696</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[02-01-2017 - 12:51:36]]></Time>
<TimeTick>1483341696</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[02-01-2017 - 12:51:42]]></Time>
<TimeTick>1483341702</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[SAP]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[02-01-2017 - 12:51:42]]></Time>
<TimeTick>1483341702</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Client.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[02-01-2017 - 12:51:42]]></Time>
<TimeTick>1483341702</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="13" >
<Disp><![CDATA[Client.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="12" >
<Disp><![CDATA[SAP]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="11" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj ><![CDATA[SAP application should be launched]]></Obj>
<Details ><![CDATA[SAP application launched successfully]]></Details>
<Time><![CDATA[02-01-2017 - 12:51:42]]></Time>
<TimeTick>1483341702</TimeTick>
<NodeArgs eType="User" icon="9" nRep="14" status="Passed" >
<Disp><![CDATA[SAP application should be launched]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[02-01-2017 - 12:51:42]]></Time>
<TimeTick>1483341702</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[SAP]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[02-01-2017 - 12:51:42]]></Time>
<TimeTick>1483341702</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Client.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[02-01-2017 - 12:51:42]]></Time>
<TimeTick>1483341702</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="17" >
<Disp><![CDATA[Client.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA["Client":Set "800"]]></Obj>
<Details plainTxt="False" ><![CDATA[Set "800"]]></Details>
<Time><![CDATA[02-01-2017 - 12:51:42]]></Time>
<TimeTick>1483341702</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="19" >
<Disp><![CDATA["Client":Set "800"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA["User":Set "otsisap"]]></Obj>
<Details plainTxt="False" ><![CDATA[Set "otsisap"]]></Details>
<Time><![CDATA[02-01-2017 - 12:51:42]]></Time>
<TimeTick>1483341702</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="21" >
<Disp><![CDATA["User":Set "otsisap"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA["Password":SetSecure "5869ff8603f7426fde3110877028c6107164d0a0dd7e47f3"]]></Obj>
<Details plainTxt="False" ><![CDATA[SetSecure "5869ff8603f7426fde3110877028c6107164d0a0dd7e47f3"]]></Details>
<Time><![CDATA[02-01-2017 - 12:51:42]]></Time>
<TimeTick>1483341702</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="23" >
<Disp><![CDATA["Password":SetSecure "5869ff8603f7426fde3110877028c6107164d0a0dd7e47f3"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA["Logon Language":Set "EN"]]></Obj>
<Details plainTxt="False" ><![CDATA[Set "EN"]]></Details>
<Time><![CDATA[02-01-2017 - 12:51:42]]></Time>
<TimeTick>1483341702</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="25" >
<Disp><![CDATA["Logon Language":Set "EN"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA["Logon Language":SetFocus]]></Obj>
<Details plainTxt="False" ><![CDATA[SetFocus]]></Details>
<Time><![CDATA[02-01-2017 - 12:51:42]]></Time>
<TimeTick>1483341702</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="27" >
<Disp><![CDATA["Logon Language":SetFocus]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[SendKey ENTER]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey ENTER]]></Details>
<Time><![CDATA[02-01-2017 - 12:51:42]]></Time>
<TimeTick>1483341702</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="29" >
<Disp><![CDATA[SendKey ENTER]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="16" >
<Disp><![CDATA[SAP]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Information_2]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[02-01-2017 - 12:51:42]]></Time>
<TimeTick>1483341702</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Continue   (Enter).Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[02-01-2017 - 12:51:42]]></Time>
<TimeTick>1483341702</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="32" >
<Disp><![CDATA[Continue   (Enter).Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="31" >
<Disp><![CDATA[Information_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[SAP Easy Access]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[02-01-2017 - 12:51:42]]></Time>
<TimeTick>1483341702</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[SAP Easy Access.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[02-01-2017 - 12:51:42]]></Time>
<TimeTick>1483341702</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="35" >
<Disp><![CDATA[SAP Easy Access.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="34" >
<Disp><![CDATA[SAP Easy Access]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[SAP]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[02-01-2017 - 12:51:42]]></Time>
<TimeTick>1483341702</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[Activate]]></Details>
<Time><![CDATA[02-01-2017 - 12:51:42]]></Time>
<TimeTick>1483341702</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="38" >
<Disp><![CDATA[Activate]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="37" >
<Disp><![CDATA[SAP]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="15" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj ><![CDATA[SAP application should navigate to home page]]></Obj>
<Details ><![CDATA[SAP application unable to navigate to home page]]></Details>
<Time><![CDATA[02-01-2017 - 12:51:42]]></Time>
<TimeTick>1483341702</TimeTick>
<NodeArgs eType="User" icon="9" nRep="39" status="Failed" >
<Disp><![CDATA[SAP application should navigate to home page]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf1.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[02-01-2017 - 12:51:42]]></Time>
<TimeTick>1483341702</TimeTick>
<NodeArgs eType="General" icon="11" nRep="40" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="02-01-2017 - 12:51:35" eTime="02-01-2017 - 12:51:42" passed="4" failed="1" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[SAP_win_Login Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="02-01-2017 - 12:50:35" eTime="02-01-2017 - 12:51:42" passed="4" failed="1" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test SAP_win_Login Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>