<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.54" os="Windows 7" host="USER-185"><DocLocation><![CDATA[D:\Tap_Framework\TAP\Scripts\SAP_Win_ChangeOrder]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[SAP_Win_ChangeOrder]]></DName>
<Res><![CDATA[Res6]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[02-01-2017 - 14:36:48]]></Time>
<TimeTick>1483348008</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="8" status="Passed" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[02-01-2017 - 14:36:48]]></Time>
<TimeTick>1483348008</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[02-01-2017 - 14:36:48]]></Time>
<TimeTick>1483348008</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[02-01-2017 - 14:36:48]]></Time>
<TimeTick>1483348008</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[SAP Easy Access]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[02-01-2017 - 14:36:48]]></Time>
<TimeTick>1483348008</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[SAP Easy Access.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[02-01-2017 - 14:36:48]]></Time>
<TimeTick>1483348008</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="13" >
<Disp><![CDATA[SAP Easy Access.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[Activate]]></Details>
<Time><![CDATA[02-01-2017 - 14:36:49]]></Time>
<TimeTick>1483348009</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" >
<Disp><![CDATA[Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA["TableTreeControl":ActivateNode "SAP Menu;Logistics;Sales and Distribution;Sales;Order;Change"]]></Obj>
<Details plainTxt="False" ><![CDATA[ActivateNode "SAP Menu;Logistics;Sales and Distribution;Sales;Order;Change"]]></Details>
<Time><![CDATA[02-01-2017 - 14:36:49]]></Time>
<TimeTick>1483348009</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="17" >
<Disp><![CDATA["TableTreeControl":ActivateNode "SAP Menu;Logistics;Sales and Distribution;Sales;Order;Change"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="12" >
<Disp><![CDATA[SAP Easy Access]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Change Sales Order: Initial]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[02-01-2017 - 14:36:49]]></Time>
<TimeTick>1483348009</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA["Order":Set "20157"]]></Obj>
<Details plainTxt="False" ><![CDATA[Set "20157"]]></Details>
<Time><![CDATA[02-01-2017 - 14:36:49]]></Time>
<TimeTick>1483348009</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="20" >
<Disp><![CDATA["Order":Set "20157"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[SendKey ENTER]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey ENTER]]></Details>
<Time><![CDATA[02-01-2017 - 14:36:50]]></Time>
<TimeTick>1483348010</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="22" >
<Disp><![CDATA[SendKey ENTER]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="19" >
<Disp><![CDATA[Change Sales Order: Initial]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Information]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[02-01-2017 - 14:36:50]]></Time>
<TimeTick>1483348010</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Information.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[02-01-2017 - 14:36:50]]></Time>
<TimeTick>1483348010</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="25" >
<Disp><![CDATA[Information.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="24" >
<Disp><![CDATA[Information]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Change Standard Order]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[02-01-2017 - 14:36:50]]></Time>
<TimeTick>1483348010</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA["All items":SetCellData 2,"Material","1400-300"]]></Obj>
<Details plainTxt="False" ><![CDATA[SetCellData 2,"Material","1400-300"]]></Details>
<Time><![CDATA[02-01-2017 - 14:36:50]]></Time>
<TimeTick>1483348010</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="28" >
<Disp><![CDATA["All items":SetCellData 2,"Material","1400-300"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA["All items":SetCellData 2,"Order Quantity","89"]]></Obj>
<Details plainTxt="False" ><![CDATA[SetCellData 2,"Order Quantity","89"]]></Details>
<Time><![CDATA[02-01-2017 - 14:36:50]]></Time>
<TimeTick>1483348010</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="30" >
<Disp><![CDATA["All items":SetCellData 2,"Order Quantity","89"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA["Save   (Ctrl+S)":Click]]></Obj>
<Details plainTxt="False" ><![CDATA[Click]]></Details>
<Time><![CDATA[02-01-2017 - 14:36:50]]></Time>
<TimeTick>1483348010</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="32" >
<Disp><![CDATA["Save   (Ctrl+S)":Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="27" >
<Disp><![CDATA[Change Standard Order]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Standard Order: Availability_2]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[02-01-2017 - 14:36:51]]></Time>
<TimeTick>1483348011</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA["Continue":Click]]></Obj>
<Details plainTxt="False" ><![CDATA[Click]]></Details>
<Time><![CDATA[02-01-2017 - 14:36:51]]></Time>
<TimeTick>1483348011</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="35" >
<Disp><![CDATA["Continue":Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="34" >
<Disp><![CDATA[Standard Order: Availability_2]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="11" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Sorry, we couldn't find D:\Upcoming Projects Preparation(Functional)\Test_Data\COSTestData.xlsx. Is it possible it was moved, renamed or deleted?<BR/>Function file: D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl<BR/>Line (157): &quot;			Set bkobj=xlobj.workbooks.open(&quot;D:\Upcoming Projects Preparation(Functional)\Test_Data\COSTestData.xlsx&quot;)&quot;.]]></Details>
<Time><![CDATA[02-01-2017 - 14:36:51]]></Time>
<TimeTick>1483348011</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="36" status="Failed" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="156" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'bkobj'<BR/>Function file: D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl<BR/>Line (158): &quot;			Set shtobj=bkobj.worksheets(&quot;Sheet1&quot;)&quot;.]]></Details>
<Time><![CDATA[02-01-2017 - 14:36:51]]></Time>
<TimeTick>1483348011</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="37" status="Failed" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="157" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'shtobj'<BR/>Function file: D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl<BR/>Line (159): &quot;			shtobj.cells(2,2)=OrderNo&quot;.]]></Details>
<Time><![CDATA[02-01-2017 - 14:36:51]]></Time>
<TimeTick>1483348011</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="38" status="Failed" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="158" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj ><![CDATA[Standard order 20157 has to be saved]]></Obj>
<Details ><![CDATA[Standard order 20157 saved successfully]]></Details>
<Time><![CDATA[02-01-2017 - 14:36:51]]></Time>
<TimeTick>1483348011</TimeTick>
<NodeArgs eType="User" icon="13" nRep="39" status="Passed" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[Standard order 20157 has to be saved]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[02-01-2017 - 14:36:52]]></Time>
<TimeTick>1483348012</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Close]]></Obj>
<Details plainTxt="False" ><![CDATA[Close]]></Details>
<Time><![CDATA[02-01-2017 - 14:36:52]]></Time>
<TimeTick>1483348012</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="42" >
<Disp><![CDATA[Close]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="41" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="02-01-2017 - 14:36:48" eTime="02-01-2017 - 14:36:58" passed="4" failed="3" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[SAP_Win_ChangeOrder Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="02-01-2017 - 14:36:47" eTime="02-01-2017 - 14:36:58" passed="4" failed="3" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test SAP_Win_ChangeOrder Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>