<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.54" os="Windows 7" host="OTSI-LAP11"><DocLocation><![CDATA[C:\Users\dkalakoti\Desktop\tap soft\SAP_Automation_25_01\TAP\Scripts\SAP_win_Login]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[SAP_win_Login]]></DName>
<Res><![CDATA[Res118]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj plainTxt="False" ><![CDATA[Add-in(s) not activated]]></Obj>
<Details plainTxt="False" ><![CDATA[The following add-in(s) were associated with your test, but are not currently loaded: 
VisualBasic.]]></Details>
<Time><![CDATA[27-03-2017 - 14:08:19]]></Time>
<TimeTick>1490603899</TimeTick>
<NodeArgs eType="Replay" icon="0" nRep="5" status="Warning" >
<Disp><![CDATA[Add-in(s) not activated]]></Disp>
</NodeArgs>
</Step>
<DIter rID="T4" iterID="1" >
<Action rID="T5">
<AName><![CDATA[Action1]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[27-03-2017 - 14:08:20]]></Time>
<TimeTick>1490603900</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" status="Passed" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[27-03-2017 - 14:08:20]]></Time>
<TimeTick>1490603900</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[27-03-2017 - 14:08:20]]></Time>
<TimeTick>1490603900</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[27-03-2017 - 14:08:26]]></Time>
<TimeTick>1490603906</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\SAP\FrontEnd\SAPgui\saplogon.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\SAP\FrontEnd\SAPgui\saplogon.exe",1]]></Details>
<Time><![CDATA[27-03-2017 - 14:08:26]]></Time>
<TimeTick>1490603906</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="15" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\SAP\FrontEnd\SAPgui\saplogon.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="14" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[SAP Logon 740]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[27-03-2017 - 14:08:30]]></Time>
<TimeTick>1490603910</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Log On.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[27-03-2017 - 14:08:30]]></Time>
<TimeTick>1490603910</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="17" >
<Disp><![CDATA[Log On.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="16" >
<Disp><![CDATA[SAP Logon 740]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj ><![CDATA[SAP application launch]]></Obj>
<Details ><![CDATA[SAP application launched successfully]]></Details>
<Time><![CDATA[27-03-2017 - 14:08:30]]></Time>
<TimeTick>1490603910</TimeTick>
<NodeArgs eType="User" icon="9" nRep="18" status="Passed" >
<Disp><![CDATA[SAP application launch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[SAP Logon 740]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[27-03-2017 - 14:08:30]]></Time>
<TimeTick>1490603910</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Log On.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-03-2017 - 14:08:30]]></Time>
<TimeTick>1490603910</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="21" >
<Disp><![CDATA[Log On.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="20" >
<Disp><![CDATA[SAP Logon 740]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[27-03-2017 - 14:08:46]]></Time>
<TimeTick>1490603926</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[SAP]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[27-03-2017 - 14:08:46]]></Time>
<TimeTick>1490603926</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Client.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[27-03-2017 - 14:08:46]]></Time>
<TimeTick>1490603926</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="25" >
<Disp><![CDATA[Client.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="24" >
<Disp><![CDATA[SAP]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="23" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj ><![CDATA[SAP Login Screen Validation]]></Obj>
<Details ><![CDATA[Screen Not Available]]></Details>
<Time><![CDATA[27-03-2017 - 14:08:46]]></Time>
<TimeTick>1490603926</TimeTick>
<NodeArgs eType="User" icon="9" nRep="26" status="Failed" >
<Disp><![CDATA[SAP Login Screen Validation]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[27-03-2017 - 14:08:50]]></Time>
<TimeTick>1490603930</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Session"&nbsp;(of&nbsp;class&nbsp;SAPGuiSession).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[27-03-2017 - 14:08:50]]></Time>
<TimeTick>1490603930</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = ses[0]<br>Mercury Class = SAPGuiSession<br>SapGui numeric component type = 12<br>]]></Details>
<Time><![CDATA[27-03-2017 - 14:08:50]]></Time>
<TimeTick>1490603930</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="30" status="Warning" nType="Description" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="29" status="Failed" nType="Run Error" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Close]]></Obj>
<Details plainTxt="False" ><![CDATA[Close]]></Details>
<Time><![CDATA[27-03-2017 - 14:10:02]]></Time>
<TimeTick>1490604002</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="32" Source="C:\Users\dkalakoti\Desktop\tap soft\SAP_Automation_25_01\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="310" >
<Disp><![CDATA[Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[27-03-2017 - 14:10:08]]></Time>
<TimeTick>1490604008</TimeTick>
<NodeArgs eType="General" icon="14" nRep="33" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="28" status="Failed" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="27-03-2017 - 14:08:19" eTime="27-03-2017 - 14:10:08" passed="5" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="7" status="Failed" >
<Disp><![CDATA[SAP_win_Login Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="27-03-2017 - 14:08:18" eTime="27-03-2017 - 14:10:08" passed="5" failed="2" warnings="2" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test SAP_win_Login Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>