<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.54" os="Windows 7" host="OTSI-LAP11"><DocLocation><![CDATA[C:\Users\dkalakoti\Desktop\tap soft\SAP_Automation_25_01\TAP\Scripts\SAP_Web_DisplayOrder]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[SAP_Web_DisplayOrder]]></DName>
<Res><![CDATA[Res2]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[27-03-2017 - 16:33:00]]></Time>
<TimeTick>1490612580</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="8" status="Passed" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[27-03-2017 - 16:33:01]]></Time>
<TimeTick>1490612581</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[27-03-2017 - 16:33:01]]></Time>
<TimeTick>1490612581</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ WebElement ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-03-2017 - 16:33:03]]></Time>
<TimeTick>1490612583</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="13" >
<Disp><![CDATA[[ WebElement ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ WebElement ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-03-2017 - 16:33:06]]></Time>
<TimeTick>1490612586</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="20" >
<Disp><![CDATA[[ WebElement ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ WebElement ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-03-2017 - 16:33:10]]></Time>
<TimeTick>1490612590</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="29" >
<Disp><![CDATA[[ WebElement ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ WebElement ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-03-2017 - 16:33:12]]></Time>
<TimeTick>1490612592</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="35" >
<Disp><![CDATA[[ WebElement ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ tree#6.105#0000000385#0#1#mi ].RightClick]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-03-2017 - 16:33:15]]></Time>
<TimeTick>1490612595</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="40" >
<Disp><![CDATA[[ tree#6.105#0000000385#0#1#mi ].RightClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ wnd[0]/usr/cntlIMAGE_CONTAINER/shellcont/shell/shellcont[0]/shell/shell/itemXXEXEC ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-03-2017 - 16:33:16]]></Time>
<TimeTick>1490612596</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="44" >
<Disp><![CDATA[[ wnd[0]/usr/cntlIMAGE_CONTAINER/shellcont/shell/shellcont[0]/shell/shell/itemXXEXEC ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Display Standard Order]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[27-03-2017 - 16:33:26]]></Time>
<TimeTick>1490612606</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Display Standard Order]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[27-03-2017 - 16:33:26]]></Time>
<TimeTick>1490612606</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Display_Order_Overview]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[27-03-2017 - 16:33:26]]></Time>
<TimeTick>1490612606</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Display_Order_Title.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[27-03-2017 - 16:33:26]]></Time>
<TimeTick>1490612606</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="49" >
<Disp><![CDATA[Display_Order_Title.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="48" >
<Disp><![CDATA[Display_Order_Overview]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="47" >
<Disp><![CDATA[Display Standard Order]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="46" >
<Disp><![CDATA[Display Standard Order]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj ><![CDATA[Display Order Overview]]></Obj>
<Details ><![CDATA[Display Order Overview Page Exists]]></Details>
<Time><![CDATA[27-03-2017 - 16:33:26]]></Time>
<TimeTick>1490612606</TimeTick>
<NodeArgs eType="User" icon="10" nRep="50" status="Passed" >
<Disp><![CDATA[Display Order Overview]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Display Standard Order]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[27-03-2017 - 16:33:26]]></Time>
<TimeTick>1490612606</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Display Standard Order]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[27-03-2017 - 16:33:26]]></Time>
<TimeTick>1490612606</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Display_Order_Overview]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[27-03-2017 - 16:33:26]]></Time>
<TimeTick>1490612606</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Order_No.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["20157"]]></Details>
<Time><![CDATA[27-03-2017 - 16:33:26]]></Time>
<TimeTick>1490612606</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="56" >
<Disp><![CDATA[Order_No.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="55" >
<Disp><![CDATA[Display_Order_Overview]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="54" >
<Disp><![CDATA[Display Standard Order]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="53" >
<Disp><![CDATA[Display Standard Order]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj ><![CDATA[Display Order Verification]]></Obj>
<Details ><![CDATA[Display Order Verification not successful]]></Details>
<Time><![CDATA[27-03-2017 - 16:33:31]]></Time>
<TimeTick>1490612611</TimeTick>
<NodeArgs eType="User" icon="10" nRep="58" status="Failed" >
<Disp><![CDATA[Display Order Verification]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="27-03-2017 - 16:32:59" eTime="27-03-2017 - 16:33:31" passed="4" failed="1" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[SAP_Web_DisplayOrder Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="27-03-2017 - 16:32:58" eTime="27-03-2017 - 16:33:31" passed="4" failed="1" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test SAP_Web_DisplayOrder Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>