<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.54" os="Windows 7" host="USER-185"><DocLocation><![CDATA[D:\Tap_Framework\TAP\Scripts\SAP_win_Login]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[SAP_win_Login]]></DName>
<Res><![CDATA[Res23]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj plainTxt="False" ><![CDATA[Add-in(s) not activated]]></Obj>
<Details plainTxt="False" ><![CDATA[The following add-in(s) were associated with your test, but are not currently loaded: 
SAP NWBC Desktop, SAPUI5, SAPWDJ, SAPWebExt.]]></Details>
<Time><![CDATA[26-12-2016 - 15:27:24]]></Time>
<TimeTick>1482746244</TimeTick>
<NodeArgs eType="Replay" icon="0" nRep="5" status="Warning" >
<Disp><![CDATA[Add-in(s) not activated]]></Disp>
</NodeArgs>
</Step>
<DIter rID="T4" iterID="1" >
<Action rID="T5">
<AName><![CDATA[Action1]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[26-12-2016 - 15:27:25]]></Time>
<TimeTick>1482746245</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="D:\Tap_Framework\TAP\Library_Files\Global\Global_Functions.qfl" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[26-12-2016 - 15:27:25]]></Time>
<TimeTick>1482746245</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[26-12-2016 - 15:27:25]]></Time>
<TimeTick>1482746245</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot connect to server &quot;192.168.1.21&quot;<BR/>Verify the server details in the SAP Logon dialog box.<BR/>Function file: D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl<BR/>Line (13): &quot;	SAPGuiUtil.OpenConnectionByIP &quot;192.168.1.21&quot;,0&quot;.]]></Details>
<Time><![CDATA[26-12-2016 - 15:27:39]]></Time>
<TimeTick>1482746259</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="13" status="Failed" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="12" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[26-12-2016 - 15:27:50]]></Time>
<TimeTick>1482746270</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[SAP]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[26-12-2016 - 15:27:50]]></Time>
<TimeTick>1482746270</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Client.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[26-12-2016 - 15:27:50]]></Time>
<TimeTick>1482746270</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="17" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[Client.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="16" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[SAP]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="15" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj ><![CDATA[SAP application should be launched]]></Obj>
<Details ><![CDATA[Unable to launch SAP application]]></Details>
<Time><![CDATA[26-12-2016 - 15:27:50]]></Time>
<TimeTick>1482746270</TimeTick>
<NodeArgs eType="User" icon="10" nRep="18" status="Failed" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[SAP application should be launched]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:01]]></Time>
<TimeTick>1482746281</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[SAP]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:01]]></Time>
<TimeTick>1482746281</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Client]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"Client"&nbsp;object's&nbsp;parent&nbsp;"Session"&nbsp;(class&nbsp;SAPGuiSession).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:01]]></Time>
<TimeTick>1482746281</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = ses[0]<br>Mercury Class = SAPGuiSession<br>SapGui numeric component type = 12<br>]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:01]]></Time>
<TimeTick>1482746281</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="23" status="Warning" nType="Parent description" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="22" status="Failed" nType="Run Error" >
<Disp><![CDATA[Client]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="21" status="Failed" >
<Disp><![CDATA[SAP]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="20" status="Failed" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:01]]></Time>
<TimeTick>1482746281</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;Client&quot; object's parent &quot;Session&quot; (class SAPGuiSession).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Function file: D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl<BR/>Line (41): &quot;	SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;SAP&quot;).SAPGuiEdit(&quot;Client&quot;).Set &quot;800&quot;&quot;.]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:01]]></Time>
<TimeTick>1482746281</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="25" status="Failed" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="40" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[SAP]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:12]]></Time>
<TimeTick>1482746292</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[User]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"User"&nbsp;object's&nbsp;parent&nbsp;"Session"&nbsp;(class&nbsp;SAPGuiSession).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:12]]></Time>
<TimeTick>1482746292</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = ses[0]<br>Mercury Class = SAPGuiSession<br>SapGui numeric component type = 12<br>]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:12]]></Time>
<TimeTick>1482746292</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="29" status="Warning" nType="Parent description" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="28" status="Failed" nType="Run Error" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[User]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="27" status="Failed" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[SAP]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="24" status="Failed" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:12]]></Time>
<TimeTick>1482746292</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;User&quot; object's parent &quot;Session&quot; (class SAPGuiSession).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Function file: D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl<BR/>Line (42): &quot;	SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;SAP&quot;).SAPGuiEdit(&quot;User&quot;).Set UID&quot;.]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:12]]></Time>
<TimeTick>1482746292</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="31" status="Failed" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="41" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[SAP]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:23]]></Time>
<TimeTick>1482746303</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Password]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"Password"&nbsp;object's&nbsp;parent&nbsp;"Session"&nbsp;(class&nbsp;SAPGuiSession).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:23]]></Time>
<TimeTick>1482746303</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = ses[0]<br>Mercury Class = SAPGuiSession<br>SapGui numeric component type = 12<br>]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:23]]></Time>
<TimeTick>1482746303</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="35" status="Warning" nType="Parent description" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="34" status="Failed" nType="Run Error" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[Password]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="33" status="Failed" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[SAP]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="30" status="Failed" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:23]]></Time>
<TimeTick>1482746303</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[SAP]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:23]]></Time>
<TimeTick>1482746303</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;Password&quot; object's parent &quot;Session&quot; (class SAPGuiSession).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Function file: D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl<BR/>Line (43): &quot;	SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;SAP&quot;).SAPGuiEdit(&quot;Password&quot;).Setsecure crypt.Encrypt(PWD)&quot;.]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:23]]></Time>
<TimeTick>1482746303</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="38" status="Failed" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="42" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Logon Language]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"Logon&nbsp;Language"&nbsp;object's&nbsp;parent&nbsp;"Session"&nbsp;(class&nbsp;SAPGuiSession).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:34]]></Time>
<TimeTick>1482746314</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = ses[0]<br>Mercury Class = SAPGuiSession<br>SapGui numeric component type = 12<br>]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:34]]></Time>
<TimeTick>1482746314</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="41" status="Warning" nType="Parent description" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="40" status="Failed" nType="Run Error" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[Logon Language]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="37" status="Failed" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[SAP]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="36" status="Failed" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:34]]></Time>
<TimeTick>1482746314</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;Logon Language&quot; object's parent &quot;Session&quot; (class SAPGuiSession).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Function file: D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl<BR/>Line (44): &quot;	SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;SAP&quot;).SAPGuiEdit(&quot;Logon Language&quot;).Set &quot;EN&quot;&quot;.]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:34]]></Time>
<TimeTick>1482746314</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="43" status="Failed" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="43" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[SAP]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:45]]></Time>
<TimeTick>1482746325</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Logon Language]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"Logon&nbsp;Language"&nbsp;object's&nbsp;parent&nbsp;"Session"&nbsp;(class&nbsp;SAPGuiSession).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:45]]></Time>
<TimeTick>1482746325</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = ses[0]<br>Mercury Class = SAPGuiSession<br>SapGui numeric component type = 12<br>]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:45]]></Time>
<TimeTick>1482746325</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="47" status="Warning" nType="Parent description" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="46" status="Failed" nType="Run Error" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[Logon Language]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="45" status="Failed" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[SAP]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="42" status="Failed" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:45]]></Time>
<TimeTick>1482746325</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;Logon Language&quot; object's parent &quot;Session&quot; (class SAPGuiSession).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Function file: D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl<BR/>Line (45): &quot;	SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;SAP&quot;).SAPGuiEdit(&quot;Logon Language&quot;).SetFocus&quot;.]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:45]]></Time>
<TimeTick>1482746325</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="49" status="Failed" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="44" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[SAP]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:56]]></Time>
<TimeTick>1482746336</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[SAP]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"SAP"&nbsp;object's&nbsp;parent&nbsp;"Session"&nbsp;(class&nbsp;SAPGuiSession).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:56]]></Time>
<TimeTick>1482746336</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = ses[0]<br>Mercury Class = SAPGuiSession<br>SapGui numeric component type = 12<br>]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:56]]></Time>
<TimeTick>1482746336</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="53" status="Warning" nType="Parent description" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="52" status="Failed" nType="Run Error" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[SAP]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="51" status="Failed" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[SAP]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="48" status="Failed" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:56]]></Time>
<TimeTick>1482746336</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;SAP&quot; object's parent &quot;Session&quot; (class SAPGuiSession).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Function file: D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl<BR/>Line (46): &quot;	SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;SAP&quot;).SendKey ENTER&quot;.]]></Details>
<Time><![CDATA[26-12-2016 - 15:28:56]]></Time>
<TimeTick>1482746336</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="55" status="Failed" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="45" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Information_2]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[26-12-2016 - 15:29:07]]></Time>
<TimeTick>1482746347</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Continue   (Enter).Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[26-12-2016 - 15:29:07]]></Time>
<TimeTick>1482746347</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="58" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[Continue   (Enter).Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="57" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[Information_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[SAP Easy Access]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[26-12-2016 - 15:29:17]]></Time>
<TimeTick>1482746357</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[SAP Easy Access.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[26-12-2016 - 15:29:17]]></Time>
<TimeTick>1482746357</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="61" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[SAP Easy Access.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="60" Source="D:\Tap_Framework\TAP\Library_Files\App_Specific\4.7\SAP_APP_Specific.qfl" SourceLine="-1" >
<Disp><![CDATA[SAP Easy Access]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[SAP]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[26-12-2016 - 15:29:25]]></Time>
<TimeTick>1482746365</TimeTick>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[SAP]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"SAP"&nbsp;object's&nbsp;parent&nbsp;"Session"&nbsp;(class&nbsp;SAPGuiSession).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[26-12-2016 - 15:29:25]]></Time>
<TimeTick>1482746365</TimeTick>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>